language: ruby
rvm:
- 2.2
install:
- travis_retry bundle install
script: bundle exec rspec
deploy:
  provider: rubygems
  api_key:
    secure: E48j1GNth8Q0m0QjTOyMksGVkFrwFJOvIPWMJy0mLlUKLmbPCm75T6i68ZURZbQuplMiRd6xwbnm8M19jrCsjMIcfU4lrGUxyzB329O4RH5H+mOnySR8cB/YIQRtAK7OdxN8uchMZVZ4TrOY63NAjmIiQLmmgHYDmd4wpbYDGOtiHCDWbGLcWy0aMb4DQQ0PgvBJb9IE7FTyxvjXXDr/DTFzfJYpzDCB1aRy0WtTXtNe452eol+VbKiFp2jx/7nJ9PabWIE0zjfRIqfmsWSobC5yRl8E+fL4uz5PedprEQt9GIDLD9uSRa4LrCvsXgRopRReDpCbCFvA63ycfA4gX5mlEw9piMWyvnTSSRcGwvsLNdnCoKbnfmZMknASJPPk6Wwr+1P6VrAvxYhl/ZgvE8XPxTu2WK/jsoLm6633Gw9wzOouOYnU3w/HVNLCbRTC5ZTajJndsdJS1aK6UFQOjtG0wxl/lX++nh2Kpps4U4I0LG4yb4hWG7tZ7ZKQbrrwDUMQgpzrdSy4bGUahrvno49BPIBTQaJlmZTM1+Hgubml84IxVFIz0NUXCIm4/rba704dEvVbNLjZqchmSwKq+0/Cwg7Zr9rn70q/UbdWap7b7KxLMFi6VvJ8xlSLqYWGyndPFgpNPPq+al/9gliM1u/MzlQW0slNdPYJtb4Y7C0=
  gem: omniauth-orcid
  on:
    tags: true
    repo: datacite/omniauth-orcid
notifications:
  slack: datacite:Wt8En0ALoTA6Kjc5EOKNDWxN
